### ISSUE TITLE
Thumbnails are just paused videos

### ISSUE THREAD

**Issue by jkosixtyfour** [catrilldev/revtube#2]
Uses shit ton of resources and bandwidth, need to fix.

**Comment by jkosixtyfour** [comment]
adding ffmpeg soon probably so maybe this will be fixed

**Comment by Cattskit** [comment]
> adding ffmpeg soon probably so maybe this will be fixed

never has been seen again

**Comment by jkosixtyfour** [comment]
forgot to close this lmfao
